version: '3.8'
services:
  backend:
    build: ./server
    container_name: backend
    ports:
      - "5001:5001"
    env_file:
      - ./server/.env
    restart: unless-stopped
    environment:
      - NODE_ENV=production 